### ISSUE TITLE
face bounding box not placed in correct locations

### ISSUE THREAD

**Issue by vabarbosa** [CODAIT/MAX-Facial-Age-Estimator-Mini-Web-App#8]
i used the facial age estimator mini app (i.e., long running demo instance):

http://max-facial-age-estimator-mini-web-app.max.us-south.containers.appdomain.cloud/

and uploaded this image:

https://github.com/IBM/MAX-Human-Pose-Estimator/blob/master/assets/Pilots.jpg

the output i got was this:

![image](https://user-images.githubusercontent.com/13156555/55877878-28759900-5b69-11e9-9748-d066acd68dea.png)

the bounding box for the faces are misplaced.

**Comment by ajbozarth** [comment]
This seems to be caused by an update to the model that was included in the recent release, I'll be rolling back that update for the long running instances and will open follow up issues to this on the main repo. I will leave this issue open for any followup needed once the model is fixed.
